server:
  port: 9999

spring:
#  jpa:
#    properties:
#      hibernate:
#        format_sql: true
#    show-sql: true
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: 'jdbc:mysql://127.0.0.1:3306/bbs?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf-8&allowPublicKeyRetrieval=true&useSSL=false'

  application:
    name: sharding-jdbc-test
  shardingsphere:
    datasource:
      ds:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://127.0.0.1:3306/bbs?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
        password: root123@
        username: root
      names: ds
    rules:
      sharding:
        binding-tables:
          - sample_data
        sharding-algorithms:
          t-order-algorithms:
            type: ORDER_HIS
        tables:
          sample_data:
            actual-data-nodes: ds.sample_data_$->{2023..2024}_$->{01..12}
            table-strategy:
              standard:
                sharding-algorithm-name: t-order-algorithms
                sharding-column: time
    props:
      sql-show: true

logging:
  level:
    org.springframework.security:
      - debug
      - info
    org.springframework.web: error
    org.hibernate.SQL: debug
    org.hibernate.engine.QueryParameters: debug
    org.hibernate.engine.query.HQLQueryPlan: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace